In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
a = np.arange(10)

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a > 5 #broadcast => element wise operation

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [7]:
a < 0

array([False, False, False, False, False, False, False, False, False,
       False])

In [8]:
np.any(a>5) # any - 한요소만 True면 True를 리턴

True

In [9]:
np.all(a>5) # all - 모든 요소가 True면 True를 리턴

False

In [10]:
test_a = np.array([1,3,0],float)
test_a

array([1., 3., 0.])